### ISSUE TITLE
extract expressions failing for some models

### ISSUE THREAD

**Issue by mattearnshaw** [NeuroML/neuroml2modelLite#1]
for example with
https://gist.github.com/mattearnshaw/3f0f3f3cf591e7390815fd82280da87a, no channels available for plotting in model desc.

however https://gist.github.com/mattearnshaw/c6f964739f647bfc8d7589eebc8c57b3 works

~~likely difference that makes a difference: `<ionChannelHH>` vs `<ionChannel type="ionChannelHH"/>`~~
must be something else because https://gist.github.com/mattearnshaw/5c1e97ef1940639707b9b0c6c7cebfe0 also not working

**Comment by borismarin** [comment]
changing defs to ionchannelhh doesn't seem to fix the problem.

2018-04-05 13:13 GMT-03:00 Matt Earnshaw <notifications@github.com>:

**Comment by pgleeson** [comment]
The issue is down to org.lemsml.model support for the gap junction comp type. See 
https://github.com/NeuroML/neuroml2model/compare/development?expand=1
The dev branch is failing due to inclusion of gap junction:
https://travis-ci.org/NeuroML/neuroml2model/jobs/363091513

I've fixed this in the lite version, making sure gap junctions are ignored.
Latest geppetto builds fine with this and can plot rate vars..

**Comment by pgleeson** [comment]
@borismarin you may want to look at support for gap junctions (down to InstanceRequirement?) in org.lemsml.model, but it's not a bottleneck here...

**Comment by borismarin** [comment]
org.lemsml.models predates tunnels and gapjunctions, I guess.

The construct that breaks things is the path at
https://github.com/NeuroML/NeuroML2/blob/master/NeuroML2CoreTypes/Synapses.xml#L472
which makes sense as we have not implemented semantics for
InstanceRequirements. Thus, things break when trying to resolve the path at
https://github.com/LEMS/org.lemsml.model/blob/development/src/main/java/org/lemsml/model/extended/PathQDParser.java#L96



2018-04-06 11:30 GMT-03:00 Padraig Gleeson <notifications@github.com>:

**Comment by pgleeson** [comment]
Well, it doesn't prevent your rates from being displayed anymore:
![selection_658](https://user-images.githubusercontent.com/1556687/38429195-a2d3665e-39b5-11e8-8e0a-d7f29a9cf219.png)
Will be on live OSB by the end of next week hopefully...
